import Link from "next/link";

import { db } from "@/lib/db";
import {
  IMAGE_ROLE_LABELS,
  STATIC_AD_STATUSES,
  STATIC_AD_STATUS_LABELS,
  type StaticAdStatus,
} from "@/lib/static-gen/status";

import { hardDeleteStaticAdAction } from "./review/actions";

export const dynamic = "force-dynamic";

// /statics is the main image inventory — defaults to "Ready" (the queue
// lander runs pull from). Every tile shows the image's assigned role so
// you can eyeball which section slots are filled at a glance.
export default async function StaticsIndexPage({
  searchParams,
}: {
  searchParams: Promise<{ status?: string }>;
}) {
  const params = await searchParams;
  const filterStatus: StaticAdStatus = isValidStatus(params.status)
    ? (params.status as StaticAdStatus)
    : "approved";

  // Normalize legacy status values so counts add up.
  const statusCounts = await Promise.all(
    STATIC_AD_STATUSES.map(async (status) => {
      const inValues =
        status === "approved"
          ? ["approved", "live", "paused"]
          : status === "archived"
            ? ["archived", "discarded"]
            : [status];
      const count = await db.staticAd.count({
        where: { status: { in: inValues } },
      });
      return { status, count };
    }),
  );

  const dbStatusFilter =
    filterStatus === "approved"
      ? { in: ["approved", "live", "paused"] }
      : filterStatus === "archived"
        ? { in: ["archived", "discarded"] }
        : filterStatus;

  const items = await db.staticAd.findMany({
    where: { status: dbStatusFilter as never },
    include: {
      adLibraryRef: { select: { filename: true, label: true } },
    },
    orderBy: { updatedAt: "desc" },
  });

  return (
    <div className="space-y-10">
      <header className="flex flex-wrap items-end justify-between gap-4">
        <div className="space-y-3">
          <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-amber-400">
            Landing-page imagery
          </p>
          <h1 className="text-4xl font-semibold leading-tight tracking-tight text-zinc-50">
            {STATIC_AD_STATUS_LABELS[filterStatus]} images
          </h1>
          <p className="max-w-xl text-sm leading-relaxed text-zinc-400">
            Every image generated by Nano Banana lives here. Ready images
            are available to drop into lander sections by role.
          </p>
        </div>
        <div className="flex items-center gap-2 text-sm">
          <Link
            href="/statics/review"
            className="rounded-lg border border-white/8 bg-white/3 px-3 py-1.5 text-xs font-semibold text-zinc-200 hover:border-white/14"
          >
            ← Review drafts
          </Link>
          <Link
            href="/statics/new"
            className="nv-cta rounded-lg px-4 py-2 text-xs"
          >
            + New batch
          </Link>
        </div>
      </header>

      <div className="flex flex-wrap items-center gap-2 text-xs">
        {statusCounts.map(({ status, count }) => {
          const active = filterStatus === status;
          return (
            <Link
              key={status}
              href={`/statics?status=${status}`}
              className={
                active
                  ? "rounded-full border border-amber-500/50 bg-amber-500/10 px-3 py-1 text-amber-300"
                  : "rounded-full border border-white/8 px-3 py-1 text-zinc-400 hover:border-white/14 hover:text-zinc-200"
              }
            >
              {STATIC_AD_STATUS_LABELS[status]}{" "}
              <span className="text-zinc-600">· {count}</span>
            </Link>
          );
        })}
      </div>

      {items.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-white/8 bg-white/1.5 p-12 text-center">
          <p className="text-sm text-zinc-500">
            No {STATIC_AD_STATUS_LABELS[filterStatus].toLowerCase()} images yet.
          </p>
        </div>
      ) : (
        <div className="grid gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
          {items.map((s) => (
            <div
              key={s.id}
              className="nv-card-hover group relative overflow-hidden rounded-2xl border border-white/6 bg-white/2"
            >
              <div className="aspect-square bg-zinc-950">
                {s.url ? (
                  /* eslint-disable-next-line @next/next/no-img-element */
                  <img
                    src={s.url}
                    alt={s.id}
                    className="h-full w-full object-cover"
                  />
                ) : (
                  <div className="flex h-full w-full items-center justify-center text-[11px] text-zinc-500">
                    no image
                  </div>
                )}
              </div>
              {s.role && (
                <span className="absolute right-2 top-2 rounded-full bg-sky-500/25 px-2 py-0.5 text-[10px] font-semibold text-sky-200 ring-1 ring-sky-500/40">
                  {IMAGE_ROLE_LABELS[s.role as keyof typeof IMAGE_ROLE_LABELS] ?? s.role}
                </span>
              )}
              <div className="flex items-center justify-between gap-2 p-2.5">
                <div className="min-w-0 flex-1">
                  <p className="truncate text-[11px] text-zinc-500">
                    from {s.adLibraryRef?.label ?? s.adLibraryRef?.filename ?? "?"}
                  </p>
                  <p className="text-[10px] text-zinc-600">
                    {new Date(s.updatedAt).toLocaleDateString()}
                  </p>
                </div>
                <form action={hardDeleteStaticAdAction}>
                  <input type="hidden" name="id" value={s.id} />
                  <button
                    type="submit"
                    className="rounded-md border border-white/6 px-2 py-1 text-[10px] text-zinc-500 opacity-0 transition-opacity group-hover:opacity-100 hover:border-rose-500/40 hover:text-rose-300"
                    title="Permanently delete"
                  >
                    ✕
                  </button>
                </form>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function isValidStatus(v: string | undefined): boolean {
  if (!v) return false;
  return (STATIC_AD_STATUSES as readonly string[]).includes(v);
}
